fix(types): conditional generic types in TS<4.1
The referred type `ConditionalRecursiveTransformExact<T, FromType, ToType>` uses
conditional generic type that is only supported in TS>=4.1. However the typesVersions
directs consumers' TSC 4.0 to the types with this definition, hence consumers will see
following error:

error TS2315: Type 'ConditionalRecursiveTransformExact' is not generic.

Changing the typesVersions directive resolves the issue.